EOSC Node AAI
EGI-Federation/egi-notebooks-hub pull request #121
Opened 2024-06-18 08:23 UTC by enolfc

- **Avoid error 500 when context is not available**
- **Add support for EOSC Node group management**

# Summary

---

**Related issue :**

2024-06-18 08:25 UTC, enolfc commented
We would benefit from some automated testing here as we are bit blind on whether this works or not :(

2024-06-20 13:12 UTC, andrea-manzi requested changes
please check comment

2024-06-20 13:17 UTC, enolfc commented on egi_notebooks_hub/egiauthenticator.py
> +    manage_groups = True
We used to fill in the groups from the user on our code, see:

https://github.com/EGI-Federation/egi-notebooks-hub/pull/121/files#diff-3109bc70e06463bd429c59fd3bdc1a0314e7ee8e6183ae7c1556b19f6e71e4a0L207

But now this is part of the oauthenticator: 
https://github.com/jupyterhub/oauthenticator/blob/72f95e7ac406cd3dc57baf26a0400b0c62456975/oauthenticator/oauth2.py#L1126

2024-06-20 13:35 UTC, andrea-manzi commented on egi_notebooks_hub/egiauthenticator.py
> +    manage_groups = True
aaaah ok, clear

2024-07-12 14:19 UTC, valtri commented
Works like a charm.

The default regular expression for personal group is OK? In testing AAI is working this: `^urn:geant:eosc-federation.eu:group:(pp-.*)$`.

And maybe we could tune `login_service` variable for EGI and EOSC authenticator? Something like:
```
    @default("login_service")
    def _login_service_default(self):
        return "EGI Check-in"
```
...but that is just a cosmetics and overrode by html customizations anyway.

2024-07-12 14:29 UTC, enolfc commented
> Works like a charm.
> 
> The default regular expression for personal group is OK? In testing AAI is working this: `^urn:geant:eosc-federation.eu:group:(pp-.*)$`.
> 
> And maybe we could tune `login_service` variable for EGI and EOSC authenticator? Something like:
> 
> ```
>     @default("login_service")
>     def _login_service_default(self):
>         return "EGI Check-in"
> ```
> 
> ...but that is just a cosmetics and overrode by html customizations anyway.

I think we can just define login_service in the EOSC one to something like "EOSC AAI", no need to define a default

2024-07-12 14:38 UTC, valtri approved these changes
LGTM!

2024-07-12 15:26 UTC, andrea-manzi approved these changes
LGTM! and tested by @valtri

2024-07-15 07:00 UTC, merged