Enable wps discovery only if configured
EGI-Federation/egi-notebooks-hub pull request #33
Opened 2021-03-25 17:48 UTC by andrea-manzi

# Summary

We enable WPS discovery only if requested, as a query to IC could be slow and it could slow down the loading of JupyterHub from the VRE

---

**Related issue :**

2021-03-25 17:52 UTC, andrea-manzi commented
ok i'll check tomorrow the lint errors

2021-03-25 21:02 UTC, enolfc requested changes
Some changes that are actually my fault...

2021-03-25 21:02 UTC, enolfc commented on egi_notebooks_hub/d4science.py
> +            self.log.info("root %s", root)
```suggestion
```

2021-03-25 21:02 UTC, enolfc commented on egi_notebooks_hub/d4science.py
> +                    self.log.info("WPS endpoint: %s", wps_endpoint)
```suggestion
                    self.log.debug("WPS endpoint: %s", wps_endpoint)
```

2021-03-25 21:02 UTC, enolfc commented on egi_notebooks_hub/d4science.py
> +                self.log.info("fetch")
These should be `.debug` more than `.info`. They were there to help me back in the day debugging the call, but maybe not really needed anymore 

```suggestion
```

2021-03-30 07:10 UTC, enolfc approved these changes
👍

2021-03-30 07:10 UTC, merged